# Generated by Django 4.0.2 on 2022-05-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='active',
        ),
        migrations.RemoveField(
            model_name='career',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='career',
            name='updated_date',
        ),
    ]
