# Generated by Django 4.0.2 on 2022-05-09 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_rename_address_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.employer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'like'), (1, 'dislike')], default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
