# Generated by Django 4.0.2 on 2022-05-10 03:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_alter_rating_employer_alter_rating_user_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='employer',
            name='address_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.CreateModel(
            name='ViewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('view', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='introduction.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('view', models.IntegerField(default=0)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='introduction.employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('company_name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='introduction.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('time_start', models.DateTimeField()),
                ('time_completed', models.DateTimeField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='introduction.profile')),
                ('university_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='introduction.university')),
            ],
        ),
        migrations.CreateModel(
            name='CVOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('intro', ckeditor.fields.RichTextField()),
                ('from_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='introduction.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
