# Generated by Django 4.0.2 on 2022-05-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0004_university_remove_profile_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='introduction.address'),
        ),
    ]
