# Generated by Django 4.0.2 on 2022-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0008_alter_recruitment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='image',
            field=models.ImageField(upload_to='recruitment/%Y/%m'),
        ),
    ]
