# Generated by Django 4.0.2 on 2022-05-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0009_alter_recruitment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='career',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='career',
            field=models.ManyToManyField(null=True, related_name='recruitment', to='introduction.Career'),
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='experience',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='experience',
            field=models.ManyToManyField(null=True, related_name='recruitment', to='introduction.Experience'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='image',
            field=models.ImageField(null=True, upload_to='recruitment/%Y/%m'),
        ),
    ]
