# Generated by Django 4.0.2 on 2022-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0010_remove_recruitment_career_recruitment_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='career',
            field=models.ManyToManyField(to='introduction.Career'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='experience',
            field=models.ManyToManyField(to='introduction.Experience'),
        ),
    ]
