# Generated by Django 4.0.2 on 2022-05-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0011_alter_recruitment_career_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='career',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment', to='introduction.career'),
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='experience',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment', to='introduction.experience'),
        ),
    ]
